theme: jekyll-theme-slate
title: CS3750 Portfolio
description: Showcasing my contributions to projects in CS 3750
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
  